# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpuGeoMemorial
                                 A QGIS plugin
 Generates descriptive memorials in the format of the SPU of the Federal Government of Brazil
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-14
        copyright            : (C) 2018 by Guilherme Henrique
        email                : guilherme.henrique@planejamento.gov.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from __future__ import absolute_import

import os
import sys
import importlib


currentDirectoryPath = os.path.dirname(__file__)
#print currentDirectoryPath

libraryDirectoryPath = os.path.join(currentDirectoryPath, 'ENV/Lib/site-packages')
#print libraryDirectoryPath
sys.path.append(libraryDirectoryPath)

libraryDirectoryPath = os.path.join(currentDirectoryPath, 'ENV/Lib/distutils')
#print libraryDirectoryPath
#name_lib_dir  = name_lib_dir +'\.qgis2\python\plugins\AzimuthDistanceCalculator\ENV\Lib\distutils'
sys.path.append(libraryDirectoryPath)

libraryDirectoryPath = os.path.join(currentDirectoryPath, 'ENV/Lib')
#print libraryDirectoryPath
#name_lib_dir  = name_lib_dir +'\.qgis2\python\plugins\AzimuthDistanceCalculator\ENV\Lib'
sys.path.append(libraryDirectoryPath)

libraryDirectoryPath = os.path.join(currentDirectoryPath, 'ENV/Lib/distutils')
#print libraryDirectoryPath
#name_lib_dir  = name_lib_dir +'\.qgis2\python\plugins\AzimuthDistanceCalculator\ENV\Lib\distutils'


sys.path.append(libraryDirectoryPath)

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpuGeoMemorial class from file SpuGeoMemorial.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    
    from .spugeo_memorial import SpuGeoMemorial
    return SpuGeoMemorial(iface)
